
[world_gen]

	#Customize ore frost crystal stone, obsidian, compressed world generation (in that order)
	[world_gen.frost_crystal]
		#Set the Y offset, Example: 
		#Offset: 4 - Sets the minimum Y height to 4.
		offset = [12, 6, 0]
		#Enable/Disable their world generation
		enable = [true, true, true]
		#Set the vein size
		vein_size = [5, 4, 3]
		#Set the vein size, Example: 
		#Range: 8 - Sets the maximum Y height to 8.
		range = [20, 10, 4]

	[world_gen.test]
		#Test List: Please Ignore
		_boolean = [true, true, false, true]
		#Test: Please Ignore
		TEST = 1
		#Enum List Test: Please Ignore
		#Allowed Values: 
		#NONE, WITHER, SLOWNESS, BLINDNESS, NAUSEA, POISON, WEAKNESS, MINING_FATIGUE, HUNGER, GLOWING, LEVITATION, IGNITE
		_enum_list = ["NONE", "IGNITE"]
		#Enum Test: Please Ignore
		#Allowed Values: NONE, NIGHT_VISION, WATER_BREATHING, STRENGTH, SPEED, HASTE, JUMP_BOOST, REGENERATION, RESISTANCE, FIRE_RESISTANCE, SATURATION, INVISIBILITY, HEALTH_BOOST, ABSORPTION, SLOW_FALLING, FLIGHT, WITHER_IMMUNITY, WATER_WEAKNESS
		_enum = "NONE"
		#Test List: Please Ignore
		_int = [1, 2, 1, 3]

	#Customize ore lava crystal stone, obsidian, compressed world generation (in that order)
	[world_gen.lava_crystal]
		#Set the Y offset, Example: 
		#Offset: 4 - Sets the minimum Y height to 4.
		offset = [12, 6, 0]
		#Enable/Disable their world generation
		enable = [true, true, true]
		#Set the vein size
		vein_size = [5, 4, 3]
		#Set the vein size, Example: 
		#Range: 8 - Sets the maximum Y height to 8.
		range = [20, 10, 4]

