
#All configuration items related to the core gameplay
[gameplay]
	#minecolonies.config.citizenvoices.comment
	citizenvoices = true

#All configurations related to pathfinding
[pathfinding]
	#Draw pathfinding paths (might be laggy). [Default: false]
	pathfindingdebugdraw = false

